ahu:
  - name: ahu01
    mat_path: ~/maro/maro/simulator/scenarios/hvac/topologies/building121/datasets/train_data_MAT.csv
    initial_values:
      dat: 75.1 # Dust Air Temperature, TODO: confirm with the one for Bonsai
      at: 15 # Air tonnage
      kw: 52.8 # kW
      mat: 40
      sps: 0.7 # Dust Static Pressure Setpoint
      das: 61 # Discharge Air Temperature Setpoint, TODO: confirm with the one for Bonsai
    transition: # TODO: Add module imported
      paths:
        model: /home/Jinyu/maro/maro/simulator/scenarios/hvac/topologies/building121/checkpoints/best_model_ep1412_loss0.023_val0.0237.pt
        x_scaler: /home/Jinyu/maro/maro/simulator/scenarios/hvac/topologies/building121/datasets/scaler/x_scaler.joblib
        y_scaler: /home/Jinyu/maro/maro/simulator/scenarios/hvac/topologies/building121/datasets/scaler/y_scaler.joblib
      input_attributes: # Not used now
        - sps
        - das
        - delta_mat_das
      output_attributes:
        - kw
        - at
        - dat
