ahu:
  - name: ahu01
    mat_path: ~/maro/maro/simulator/scenarios/hvac/topologies/building121/datasets/train_data_MAT.csv
    initial_values:
      dat: 54.7 # Dust Air Temperature, 75.1, TODO: confirm with the one for Bonsai
      at: 51 # Air tonnage, 51
      kw: 87.6 # kW, 52.8
      mat: 68.3 # 40
      sps: 0.7 # Dust Static Pressure Setpoint
      das: 54.3 # Discharge Air Temperature Setpoint, 61, TODO: confirm with the one for Bonsai
    transition: # TODO: Add module imported
      paths:
        model: /home/Jinyu/maro/maro/simulator/scenarios/hvac/topologies/building121/checkpoints/best_model_ep1412_loss0.023_val0.0237.pt
        x_scaler: /home/Jinyu/maro/maro/simulator/scenarios/hvac/topologies/building121/datasets/scaler/x_scaler.joblib
        y_scaler: /home/Jinyu/maro/maro/simulator/scenarios/hvac/topologies/building121/datasets/scaler/y_scaler.joblib
      input_attributes: # Not used now
        - sps
        - das
        - delta_mat_das
      output_attributes:
        - kw
        - at
        - dat
