# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

mode: local # local, distributed
num_episodes: 100
num_steps: -1
eval_schedule: 50
env:
  basic:
    scenario: cim
    topology: toy.4p_ssdd_l0.0
    durations: 1120
  wrapper:
    port_attributes:
      - empty
      - full
      - on_shipper
      - on_consignee
      - booking
      - shortage
      - fulfillment
    vessel_attributes:
      - empty
      - full
      - remaining_space
    num_actions: 21
    # Parameters for computing states
    look_back: 7
    max_ports_downstream: 2
    # Parameters for computing actions
    finite_vessel_space: true
    has_early_discharge: true
    # Parameters for computing rewards
    reward_eval_delay: 99
    fulfillment_factor: 1.0
    shortage_factor: 1.0
    time_decay: 0.97
exploration:
  last_ep: 100
  initial_value: 0.4
  final_value: 0.0
  splits:
    - [50, 0.32]
policy:
  model:
    network:
      hidden_dims:
        - 256
        - 128
        - 64
      activation: leaky_relu
      softmax: false
      batch_norm: true
      skip_connection: false
      head: true
      dropout_p: 0.0
    optimization:
      optim_cls: rmsprop
      optim_params:
        lr: 0.05
  algorithm_config:
    reward_discount: .0
    target_update_freq: 5
    train_epochs: 10
    gradient_iters: 1
    soft_update_coefficient: 0.1
    double: false
    loss_cls: smooth_l1
  experience_memory:
    capacity: 1000000
    overwrite_type: "rolling"
  sampling:
    batch_size: 128
distributed:
  group: cim-dqn
  num_actors: 3
  redis_host: localhost
  redis_port: 6379
  required_actor_finishes: 2
