# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job_name: sc 
scenario: supply_chain
mode: sync
num_episodes: 3
eval_schedule: 3 
num_steps: -1
max_lag: 0
log_env_summary: false
sync:
  rollout_group: rollout
  rollout_mode: multi-node # single-process, multi-process, multi-node
  num_rollout_workers: 5
  # min_finished_workers: 4
  # max_extra_recv_tries: 3
  # extra_recv_timeout: 100
async:
  group: async
  num_actors: 3
policy_manager:
  train_group: policy-manager
  train_mode: multi-node # single-process, multi-process, multi-node
  num_trainers: 3
redis:
  host: maro-redis
  port: 6379
