# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job: supply_chain
scenario: supply_chain
mode: sync  # single, sync, async
num_episodes: 3
eval_schedule: 3
num_steps: -1
max_lag: 0
sync:
  num_rollouts: 3
  num_eval_rollouts: 1
  rollout_type: distributed   # multi-process, distributed
  distributed:
    group: rollout
    min_finished_workers: 2
    max_extra_recv_tries: 1
    extra_recv_timeout: 200
async:
  group: async
  num_rollouts: 3
policy_manager:
  type: distributed   # simple, distributed
  simple:
    parallel: true
  distributed:
    group: learn
    num_hosts: 2
redis:
  host: redis-server
  port: 6379
