# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job_name: sc 
scenario: sc
mode: sync
num_episodes: 5
eval_schedule: 3 
num_steps: -1
max_lag: 0
log_env_summary: false
sync:
  rollout_group: rollout
  rollout_mode: multi-node # single-process, multi-process, multi-node
  num_rollout_workers: 2
  # max_receive_attempts: 2
  # receive_timeout: 100  # in milli-seconds
async:
  group: async
  num_actors: 3
policy_manager:
  train_group: policy-manager
  train_mode: multi-node # single-process, multi-process, multi-node
  num_trainers: 4
redis:
  host: maro-redis
  port: 6379