# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job: cim
scenario_dir: "/home/yaqiu/maro/examples/rl/cim"
#load_policy_dir: "/home/yaqiu/maro/examples/rl/checkpoints/cim"
checkpoint_dir: "/home/yaqiu/maro/examples/rl/checkpoints/cim"
log_dir: "/home/yaqiu/maro/examples/rl/logs"
mode: async  # single, sync, async
num_episodes: 2
# eval_schedule: 2
sync:
  num_rollouts: 3
  num_eval_rollouts: 1
  rollout_type: distributed   # multi-process, distributed
  distributed:
    min_finished_workers: 2
    max_extra_recv_tries: 1
    extra_recv_timeout: 200
async:
  max_lag: 3
  num_rollouts: 3
policy_manager:
  type: distributed   # simple, multi-process, distributed
  distributed:
    num_hosts: 2
data_parallelism: 1
redis:
  host: maro
  port: 6379