# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job: supply_chain
scenario_dir: "/maro/examples"
scenario: supply_chain
load_policy_dir: "/maro/examples/checkpoints/cim4"
checkpoint_dir: "/maro/examples/checkpoints/cim4"
log_dir: "/maro/examples/logs/cim4"
mode: sync  # single, sync, async
num_episodes: 10
eval_schedule: 5
sync:
  num_rollouts: 3
  num_eval_rollouts: 1
  rollout_type: distributed   # multi-process, distributed
  distributed:
    min_finished_workers: 2
    max_extra_recv_tries: 1
    extra_recv_timeout: 200
async:
  num_rollouts: 3
policy_manager:
  type: distributed   # simple, multi-process, distributed
  distributed:
    num_hosts: 2
redis:
  host: maro
  port: 6379