apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
      - command: python3 /rltest/workflows/synchronous/learner.py
        image: maroacr.azurecr.cn/marorl
        imagePullPolicy: Always
        name: learner
        volumeMounts:
        - mountPath: /rltest
          name: maro
      nodeSelector:
        agentpool: sc
      restartPolicy: Never
      volumes:
      - azureFile:
          readOnly: false
          secretName: azure-secret
          shareName: rltest
        name: maro
